[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4" 
image = "0.24.7"
rayon = "1.8.0"
easy-gltf="1.1.1"
